server:
  port: 9099
spring:
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/graph_site
    username: root
    password: 123456
logging:
  level:
    root: info